<?php
define("Head_Part","Head/");
define("Body_Part","Body/");
define("Footer_Part","Footer/");
define("IMG_Path","images/");
define("CSS_Path","css/");
define("JS_Path","js/");
define("PAGES","Pages/");
define("DATABASE","Database/");
define("PG_Path","plugins/");
define("DIST_Path","dist/");
define("MAIL","Mail/");
define("CART","cart/");
define("CHANGEPASSWORD","changepassword/");
define("CONTACT","contact/");
define("DETAIL","detail/");
define("HANDBAG","handbag/");
define("HOME","home/");
define("INFORMATION","information/");
define("ORDER","order/");
define("PANT","pant/");
define("RESULT","result/");
define("SALE","sale/");
define("SERVICE","service/");
define("SHOES","shoes/");
define("SIGN","sign/");
define("TSHIRT","t-shirt/");
define("CUSTOMER","customer/");
?>