<?php
$level="../";
$IsIndex=false;
$IsContact=false;
$IsDetails=false;
$IsPants=false;
$IsHandbags=false;
$IsSale=false;
$IsService=false;
$IsShoes=false;
$IsTshirts=false;
$IsSignin=false;
$IsSignup=false;
$IsKetqua=true;
$IsCart=false;
$IsInformation=false;
$IsChangePassword=false;
$IsOrder=false;
$IsKetquaOrder=false;
$IsDetailOrder=false;
$IsForgotPassword=false;
$IsPasswordRecovery=false;
include($level."Config.php");
include($level."Layout.php");
?>